### Linear Algebra Application for Machine Learning

In [40]:
# Import libraries
import numpy as np

In [41]:
# Create a 2D array
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [42]:
# Create a 3D array
B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(B)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
# Create a 3D array of zeros
C = np.zeros((2, 3, 4))
print(C)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [44]:
# Create a 3D array of ones
D = np.ones((2, 3, 4))
print(D)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [45]:
# Create a 3D array of random numbers
E = np.random.random((2, 3, 4))
print(E)

[[[0.78482165 0.23682398 0.96505873 0.15176861]
  [0.82130624 0.274829   0.51945669 0.46858508]
  [0.10061017 0.83901226 0.80005983 0.64625047]]

 [[0.75613277 0.99232157 0.78068993 0.43506969]
  [0.54657391 0.8222663  0.0640511  0.10124143]
  [0.31504307 0.22173163 0.79438862 0.5742397 ]]]


In [46]:
# Create a 3D array of random integers
F = np.random.randint(10, size=(3, 4, 5))
print(F)

[[[4 2 4 9 1]
  [6 3 5 8 4]
  [9 2 3 0 5]
  [3 0 4 9 9]]

 [[1 3 2 1 0]
  [7 0 8 8 7]
  [7 1 0 3 5]
  [5 3 8 6 1]]

 [[0 3 1 5 9]
  [8 2 5 1 4]
  [2 9 5 7 5]
  [8 2 4 0 3]]]


In [47]:
# Create a 3D array of random integers
G = np.random.randint(10, size=(3, 4, 5))
print(G)

[[[2 7 9 6 7]
  [0 6 1 3 8]
  [6 5 0 2 0]
  [4 6 2 8 8]]

 [[5 8 2 0 8]
  [8 1 9 8 1]
  [8 1 0 5 2]
  [6 4 7 0 9]]

 [[8 9 4 9 9]
  [2 5 8 7 0]
  [6 5 2 1 7]
  [8 7 5 4 0]]]


In [48]:
# Create a function calculate the dot product of two vectors
def dot_product(a, b):
    return sum([a[i] * b[i] for i in range(len(a))])

# Write the test for the dot product function
def test_dot_product():
    a = [1, 2, 3]
    b = [4, 5, 6]
    assert dot_product(a, b) == 32
    print("Test passed!")

test_dot_product()

Test passed!


In [49]:
# Create a function calculate the sum of two vectors
def vector_sum(a, b):
    return [a[i] + b[i] for i in range(len(a))]

# Write the test for the vector sum function
def test_vector_sum():
    a = [1, 2, 3]
    b = [4, 5, 6]
    assert vector_sum(a, b) == [5, 7, 9]
    print("Test passed!")

test_vector_sum()

Test passed!


In [50]:
# Create a function calculate the sum of multiple vectors
def vector_sum(*args):
    return [sum(arg[i] for arg in args) for i in range(len(args[0]))]

# Write the test for the vector sum function
def test_vector_sum():
    a = [1, 2, 3]
    b = [4, 5, 6]
    c = [7, 8, 9]
    assert vector_sum(a, b, c) == [12, 15, 18]
    print("Test passed!")

test_vector_sum()

Test passed!


In [51]:
# Create a function calculate the subtraction of two vectors
def vector_subtract(a, b):
    return [a[i] - b[i] for i in range(len(a))]

# Write the test for the vector subtraction function
def test_vector_subtract():
    a = [1, 2, 3]
    b = [4, 5, 6]
    assert vector_subtract(a, b) == [-3, -3, -3]
    print("Test passed!")

test_vector_subtract()

Test passed!


In [52]:
# Create a function calculate the subtraction of two matrices
def matrix_subtract(a, b):
    return [vector_subtract(a[i], b[i]) for i in range(len(a))]

# Write the test for the matrix subtraction function
def test_matrix_subtract():
    a = [[1, 2, 3], [4, 5, 6]]
    b = [[7, 8, 9], [10, 11, 12]]
    assert matrix_subtract(a, b) == [[-6, -6, -6], [-6, -6, -6]]
    print("Test passed!")

# Create a function calculate the sum of two matrices
def matrix_sum(a, b):
    return [vector_sum(a[i], b[i]) for i in range(len(a))]

# Write the test for the matrix sum function
def test_matrix_sum():
    a = [[1, 2, 3], [4, 5, 6]]
    b = [[7, 8, 9], [10, 11, 12]]
    assert matrix_sum(a, b) == [[8, 10, 12], [14, 16, 18]]
    print("Test passed!")

test_matrix_subtract()
test_matrix_sum()

Test passed!
Test passed!


In [53]:
# Create a function calculate determinant of a matrix
def matrix_determinant(a):
    if len(a) == 1:
        return a[0][0]
    else:
        return sum([(-1) ** i * a[0][i] * matrix_determinant([row[:i] + row[i+1:] for row in a[1:]]) for i in range(len(a))])

# Write the test for the matrix determinant function
def test_matrix_determinant():
    a = [[1, 2], [3, 4]]
    assert matrix_determinant(a) == -2
    print("Test passed!")

test_matrix_determinant()

Test passed!


In [54]:
# Create a function calculate the transpose of a matrix
def matrix_transpose(a):
    return [[row[i] for row in a] for i in range(len(a[0]))]

# Write the test for the matrix transpose function
def test_matrix_transpose():
    a = [[1, 2], [3, 4]]
    assert matrix_transpose(a) == [[1, 3], [2, 4]]
    print("Test passed!")

test_matrix_transpose()

Test passed!


In [55]:
# Create a function calculate eigenvalues of a matrix
def matrix_eigenvalues(a):
    return np.linalg.eigvals(a)

print(matrix_eigenvalues([[1, 2], [3, 4]]))

[-0.37228132  5.37228132]


In [56]:
# Create a function calculate eigenvectors of a matrix
def matrix_eigenvectors(a):
    return np.linalg.eig(a)[1]

print(matrix_eigenvectors([[1, 2], [3, 4]]))

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [57]:
# Create a function calculate the inverse of a matrix
def matrix_inverse(a):
    return np.linalg.inv(a)

print(matrix_inverse([[1, 2], [3, 4]]))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [58]:
# Create a function find the rank of a matrix
def matrix_rank(a):
    return np.linalg.matrix_rank(a)

# Write the test for the matrix rank function
def test_matrix_rank():
    a = [[1, 2], [3, 4]]
    assert matrix_rank(a) == 2
    print("Test passed!")

# Create a function calculate the trace of a matrix
def matrix_trace(a):
    return sum([a[i][i] for i in range(len(a))])

# Write the test for the matrix trace function
def test_matrix_trace():
    a = [[1, 2], [3, 4]]
    assert matrix_trace(a) == 5
    print("Test passed!")

test_matrix_rank()
test_matrix_trace()

Test passed!
Test passed!


In [69]:
# Create a function compute Singular Value Decomposition of a matrix
def matrix_svd(a):
    return np.linalg.svd(a)
# Create a function compute the Moore-Penrose pseudoinverse of a matrix
def matrix_pseudoinverse(a):
    return np.linalg.pinv(a)

In [70]:
matrix_svd([[1, 2], [3, 4]])

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [71]:
matrix_pseudoinverse([[1, 2], [3, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])