#### What are Tensors?

> A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

> A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second order tensor.

> Tensor notation is much like matrix notation with a capital letter representing a tensor and lowercase letters with
subscript integers representing scalar values within the tensor.

> Many of the operations that can be performed with scalars, vectors, and matrices can be reformulated to be performed
with tensors.

> As a tool, tensors and tensor algebra is widely used in the fields of physics and engineering. It is a term and set of
techniques known in machine learning in the training and operation of deep learning models can be described in terms
of tensors.

#### Example of creating a tensor from a list of data with NumPy and Pytorch

In [3]:
import numpy as np
import torch

In [4]:
# define a list of data
data = [[1, 2],[3, 4]]

In [5]:
# create a tensor from data
x_data = torch.tensor(data)

In [6]:
# Example of creating a tensor from a NumPy array
# define a numpy array
np_array = np.array(data)

# create a tensor from a numpy array
x_np = torch.from_numpy(np_array)

In [7]:
# Example of creating a tensor from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data

In [8]:
# Example of creating a tensor with random or constant values
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [9]:
# Example of tensor attributes
tensor = torch.rand(3, 4)

In [10]:
# print the shape of a tensor
print('Shape of tensor:', tensor.shape)

Shape of tensor: torch.Size([3, 4])


In [11]:
# print the datatype of a tensor
print('Datatype of tensor:', tensor.dtype)

Datatype of tensor: torch.float32


In [12]:
# print the device tensor is stored on (CPU or GPU)
print('Device tensor is stored on:', tensor.device)

Device tensor is stored on: cpu


#### Example of tensor operations

In [15]:
# We can use all familiar operations with tensors
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
# Concatenate two tensors along dimension 0 (vertical stacking)
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# Concatenate two tensors along dimension 1 (horizontal stacking)
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [18]:
# We can do the same for matrices
matrix1 = torch.ones(2, 5)
matrix2 = torch.zeros(3, 5)
print(torch.cat([matrix1, matrix2], dim=0).shape)

torch.Size([5, 5])


In [19]:
# Arithmetic operations are similar to NumPy
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [22]:
# Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [23]:
# In-place operations
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [25]:
# Bridge with NumPy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [26]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
